export const FETCH_SHOWS_PENDING = "FETCH_SHOWS_PENDING";
export const FETCH_SHOWS_SUCCESS = "FETCH_SHOWS_SUCCESS";
export const FETCH_EPISODES_PENDING = "FETCH_EPISODES_PENDING";
export const FETCH_EPISODES_SUCCESS = "FETCH_EPISODES_SUCCESS";
export const SHOW_SELECTED = "SHOW_SELECTED";
export const EPISODE_SELECTED = "EPISODE_SELECTED";
export const FETCH_SHOWS_ERROR = "FETCH_SHOWS_ERROR";
export const FETCH_EPISODES_ERROR = "FETCH_EPISODES_ERROR";
